### ISSUE TITLE
Selected code in graphiql editor is not identifiable

### ISSUE THREAD

**Issue by paulmelero** [chenkie/try-graphql#1]
This whole query is "selected":

![image](https://user-images.githubusercontent.com/6775220/53186363-27ac9600-3601-11e9-9231-1fa7834d7bb9.png)

Seems to be a problem with the CSS. But, the blocks of `.CodeMirror-selected` that are being created are worrying me a little. So, no clue here. Maybe it's a problem with `graphiql-material-theme` or you are overriding these styles somewhere.

BTW, thank you very much for this amazing resource!!

**Comment by chenkie** [comment]
Ah thanks! This looks different locally for some reason 🤔

And I appreciate the kind words!

**Comment by chenkie** [comment]
fixed in latest!
